// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgBc4oaYJu1fPkq1n6w9O7NFmhWLrpS40',
    appId: '1:417754298541:web:0b423762304348b6e3ae24',
    messagingSenderId: '417754298541',
    projectId: 'tasky-db-8ea78',
    authDomain: 'tasky-db-8ea78.firebaseapp.com',
    storageBucket: 'tasky-db-8ea78.appspot.com',
    measurementId: 'G-9Z42C8BWC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfzbsRo05hbeZncesSXCPZ8cBC2YIw1sQ',
    appId: '1:417754298541:android:7a0f4da32fff7bace3ae24',
    messagingSenderId: '417754298541',
    projectId: 'tasky-db-8ea78',
    storageBucket: 'tasky-db-8ea78.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgBc4oaYJu1fPkq1n6w9O7NFmhWLrpS40',
    appId: '1:417754298541:web:b5722056060585c8e3ae24',
    messagingSenderId: '417754298541',
    projectId: 'tasky-db-8ea78',
    authDomain: 'tasky-db-8ea78.firebaseapp.com',
    storageBucket: 'tasky-db-8ea78.appspot.com',
    measurementId: 'G-3QDRR74QC3',
  );

}